hmrc/income-tax-software-choices-frontend

- app/assets/javascript/softwareSearch.js
- app/assets/stylesheets/application.scss
- app/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/controllers/SearchSoftwareController.scala
- app/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/forms/FiltersForm.scala
- app/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/models/FiltersFormModel.scala
- app/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/models/VendorFilter.scala
- app/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/services/SoftwareChoicesService.scala
- app/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/SearchSoftwarePage.scala.html
- app/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/SoftwareVendorsTemplate.scala.html
- conf/messages
- it/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/controllers/SearchSoftwareControllerISpec.scala
- scripts/start
- test/resources/test-valid-software-vendors.json
- test/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/controllers/SearchSoftwareControllerSpec.scala
- test/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/services/SoftwareChoicesServiceSpec.scala
- test/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/SearchSoftwareViewSpec.scala
> ITSASU-1406: Filter-Pricing

- app/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/SearchSoftwarePage.scala.html
- Remove unnecessary “type” attribute for JavaScript resources.
> Fix VNU violation:

- app/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/forms/FiltersForm.scala
- app/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/models/VendorFilter.scala
- app/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/SearchSoftwarePage.scala.html
- conf/messages
- conf/software-vendors.json
- test/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/forms/FiltersFormSpec.scala
- test/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/SearchSoftwareViewSpec.scala
> ITSASU-1416: Software compatibility filters

- app/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/models/VendorFilter.scala
- app/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/SearchSoftwarePage.scala.html
- build.sbt
- conf/messages
- conf/software-vendors.json
- test/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/forms/FiltersFormSpec.scala
- test/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/SearchSoftwareViewSpec.scala
> ITSASU-1437: Add Mandated Income Type filters

- conf/application.conf
> ITSASU-1451: Add Tracking-Consent-Frontend config

- app/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/config/AppConfig.scala
- app/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/templates/MainTemplate.scala.html
- test/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/MainTemplateViewSpec.scala
- test/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/SearchSoftwareViewSpec.scala
> ITSASU-1425: Add beta phase banner

- app/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/SoftwareVendorsTemplate.scala.html
- conf/messages
- test/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/SearchSoftwareViewSpec.scala
> ITSASU-1497: Implement no search results text

- app/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/models/SoftwareVendorModel.scala
- app/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/ProductDetailsPage.scala.html
- conf/messages
- conf/software-vendors.json
- test/resources/test-valid-software-vendors.json
- test/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/models/SoftwareVendorModelSpec.scala
- test/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/models/SoftwareVendorsSpec.scala
- test/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/services/SoftwareChoicesServiceSpec.scala
- test/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/ProductDetailsPageViewSpec.scala
- test/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/SearchSoftwareViewSpec.scala
> ITSASU-1528: BETA - Email Contact Link for Software Provider

- app/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/SearchSoftwarePage.scala.html
- app/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/SoftwareFiltersTemplate.scala.html
- app/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/SoftwareFiltersTemplateAlpha.scala.html
- app/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/helpers/CheckboxGroupHelper.scala.html
- test/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/SearchSoftwareViewSpec.scala
> ITSASU-1612: Move filter page accordion menu behind feature switch

- app/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/models/SoftwareVendorModel.scala
- app/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/ProductDetailsPage.scala.html
- test/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/helpers/TestModels.scala
- test/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/models/SoftwareVendorModelSpec.scala
- test/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/models/SoftwareVendorsSpec.scala
- test/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/services/SoftwareChoicesServiceSpec.scala
- test/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/ProductDetailsViewSpec.scala
- test/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/SearchSoftwareViewSpec.scala
> ITSASU-1629: Update email and phone number to be optional

- conf/software-vendors.json
Is this really all I need to do?
> [ITSASU-1625] Add FreeAgent software vendor

- conf/software-vendors.json
> ITSASU-1624: Added VitalTax to vendor config

- conf/software-vendors.json
> ITSASU-1646: Fix VitalTax issues

- conf/software-vendors.json
> ITSASU-1609: Add Sage software provider data

- conf/software-vendors.json
> ITSASU-1651: fix invalid number

- app/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/SoftwareVendorsTemplate.scala.html
- app/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/SoftwareVendorsTemplateAlpha.scala.html
- conf/messages
- conf/messages.cy
- test/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/config/MessagesSpec.scala
- test/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/helpers/MessagesMatcher.scala
> ITSASU-1665: Ensure Welsh provision for Beta Features text

- app/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/controllers/GlossaryController.scala
- app/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/GlossaryPage.scala.html
- conf/messages
- conf/messages.cy
- test/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/controllers/GlossaryControllerSpec.scala
- test/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/GlossaryViewSpec.scala
Gets a chunk of the actual content done
Does the last changed date and other bits now agreed on the prototype
Uses html for the RH column instead of plain text, so we can have links
> Add content to Glossary page.

- app/assets/stylesheets/application.scss
> ITSASU-1897: Aud. #10 - Search icon colour and size

- app/assets/javascript/softwareSearch.js
- app/assets/stylesheets/application.scss
- app/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/SearchSoftwarePage.scala.html
- test/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/SearchSoftwareViewSpec.scala
Submit now automatic for js enabled, and triggered by clicking either a text search button or an "apply-filters" button when not js-enabled.
> [ITSASU-1901] Remove apply-filters. Change submit behaviour.

- app/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/GlossaryPage.scala.html
- app/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/ProductDetailsPage.scala.html
- app/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/SearchSoftwarePage.scala.html
- app/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/templates/MainTemplate.scala.html
- test/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/GlossaryViewSpec.scala
- test/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/ProductDetailsViewSpec.scala
- test/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/SearchSoftwareViewSpec.scala
> ITSASU-1902: Aud. #11 - Breadcrumbs

- app/assets/stylesheets/application.scss
> ITSASU-1897: Fix search button active state

- app/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/SearchSoftwarePage.scala.html
- app/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/templates/SoftwareSearchStatusTemplate.scala.html
- app/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/templates/SoftwareVendorsTemplate.scala.html
- app/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/templates/SoftwareVendorsTemplateAlpha.scala.html
- conf/messages
- test/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/controllers/SearchSoftwareControllerSpec.scala
- test/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/SearchSoftwareViewSpec.scala
> ITSASU-1950: Fix beta search status A11Y issue

- app/assets/javascript/glossarySearch.js
- app/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/controllers/GlossaryController.scala
- app/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/GlossaryPage.scala.html
- app/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/templates/GlossaryItemsTemplate.scala.html
- app/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/views/templates/GlossarySearchStatusTemplate.scala.html
- project/build.properties
- test/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/controllers/GlossaryControllerSpec.scala
> ITSASU-1951: Fix glossary search A11Y issue

- app/uk/gov/hmrc/incometaxsoftwarechoicesfrontend/repositories/UserFiltersRepository.scala
- conf/application.conf
Changed replaceIndexes back to false after deploying previous ticket (ITSASU 4149)
> Itsasu4207
